title: MoviesFLIX
baseurl: ""
url: "http://localhost:4000"

plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: pretty
collections:
  bollywood:
    output: true
    permalink: /:collection/:categories/:name/
  hollywood:
    output: true
    permalink: /:collection/:categories/:name/